# Generated by Django 4.2.1 on 2023-06-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
